name: PHP CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  app_step_check:

    runs-on: ubuntu-latest

    env:
      APP_ENV: test

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: fizzbuzz
          MYSQL_USER: app
          MYSQL_PASSWORD: app
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl, xml, pdo_mysql
          tools: composer:v2
          coverage: none

      - name: Display PHP and Composer versions
        run: |
          php -v
          composer --version

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Prepare database
        run: |
            php bin/console doctrine:database:create --if-not-exists --env=test
            php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPStan
        run: composer phpstan

      - name: Check code style
        run: composer cs-fixer-check

      - name: Architecture check
        run: composer deptrac

      - name: Run tests
        run: composer test
